### ISSUE TITLE
Firefox - cannot register - round icon

### ISSUE THREAD

**Issue by yaronf** [yaronf/overlay-clock#9]
Fails registration as a FF add-on. The only error is:
```
Error: Icon at "icon48.png" must be square.
```

**Comment by chelovechishko** [comment]
Hope it's ok: `gm convert -extent 48x48-0-9 -compose Copy icon48.png`
![icon49](https://user-images.githubusercontent.com/14850730/94462858-15400880-01f7-11eb-8515-83ff130d53ec.png)

**Comment by yaronf** [comment]
Looks good.
